/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SunRouteImport } from './routes/sun'
import { Route as MonumentRouteImport } from './routes/monument'

const SunRoute = SunRouteImport.update({
  id: '/sun',
  path: '/sun',
  getParentRoute: () => rootRouteImport,
} as any)
const MonumentRoute = MonumentRouteImport.update({
  id: '/monument',
  path: '/monument',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/monument': typeof MonumentRoute
  '/sun': typeof SunRoute
}
export interface FileRoutesByTo {
  '/monument': typeof MonumentRoute
  '/sun': typeof SunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/monument': typeof MonumentRoute
  '/sun': typeof SunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/monument' | '/sun'
  fileRoutesByTo: FileRoutesByTo
  to: '/monument' | '/sun'
  id: '__root__' | '/monument' | '/sun'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MonumentRoute: typeof MonumentRoute
  SunRoute: typeof SunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sun': {
      id: '/sun'
      path: '/sun'
      fullPath: '/sun'
      preLoaderRoute: typeof SunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monument': {
      id: '/monument'
      path: '/monument'
      fullPath: '/monument'
      preLoaderRoute: typeof MonumentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  MonumentRoute: MonumentRoute,
  SunRoute: SunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
