/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SunRouteImport } from './routes/sun'

const SunRoute = SunRouteImport.update({
  id: '/sun',
  path: '/sun',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/sun': typeof SunRoute
}
export interface FileRoutesByTo {
  '/sun': typeof SunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/sun': typeof SunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/sun'
  fileRoutesByTo: FileRoutesByTo
  to: '/sun'
  id: '__root__' | '/sun'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SunRoute: typeof SunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sun': {
      id: '/sun'
      path: '/sun'
      fullPath: '/sun'
      preLoaderRoute: typeof SunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SunRoute: SunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
